import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Adarsh",
    lastName: "Balika",
    username: "adarshbalika",
    password: "adarshBalika123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Sharing my happy thoughts",
    portfolio: "https://www.lipsum.com/",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "Abhishek",
    lastName: "Sahani",
    username: "abhishekSahani",
    password: "abhishekSahani123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar:
      "https://media-exp1.licdn.com/dms/image/C5603AQEqEDNWTDG0UQ/profile-displayphoto-shrink_200_200/0/1630987867284?e=1664409600&v=beta&t=d6uKvEjdpd-jVesvCh-gwCBsQdQ3YEcNr3gtjE31Npw",
    bio: "A Homosapien evolved to do software development, storytelling and art",
    portfolio: "https://abhishek-sahani.web.app/",
    celeb: true,
  },
  {
    _id: uuid(),
    firstName: "Riya",
    lastName: "Garg",
    username: "riyaGarg",
    password: "riyaGarg123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/kristy.png",
    bio: "Trying to be a rainbow in someone’s cloud.",
    portfolio:
      "http://ankunding.com/vel-facilis-repudiandae-dolores-neque-quis",
    celeb: true,
  },
  {
    _id: uuid(),
    firstName: "Akshay",
    lastName: "Kumar",
    username: "akshayKumar",
    password: "akshayKumar123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar:
      "https://pbs.twimg.com/profile_images/1513413525187743746/JVdygchC_400x400.jpg",
    bio: "Actor",
    portfolio: "http://www.schmitt.com/esse-dolorem-dolorum-maxime",
    celeb: true,
  },
  {
    _id: uuid(),
    firstName: "MS",
    lastName: "Dhoni",
    username: "msDhoni",
    password: "msDhoni123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU6BOwb5LswFo1EPk8hCMdmCPL6F5nyQ5OAw&usqp=CAU",
    bio: "The Finisher",
    portfolio:
      "http://www.haley.biz/nesciunt-sit-similique-earum-unde-expedita-quo-necessitatibus",
    celeb: true,
  },
  {
    _id: uuid(),
    firstName: "Shubham",
    lastName: "Soni",
    username: "shubhamsoni",
    password: "shubhamsoni123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Time is precious, waste it wisely.",
    portfolio: "https://semantic-soni.web.app",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "Soham",
    lastName: "Shah",
    username: "sohamshah",
    password: "sohamShah123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Dreamer",
    portfolio: "https://www.casper.com/qui-enim-hic-vero-incidunt",
    celeb: false,
  },

  {
    _id: uuid(),
    firstName: "Arjun",
    lastName: "Sharma",
    username: "arjunsharma",
    password: "arjunSharma123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Archer",
    portfolio:
      "http://bashirian.net/adipisci-dolor-consequuntur-nesciunt-facilis-dolor-quia-rem",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "Sunny",
    lastName: "Singh",
    username: "sunnysingh",
    password: "sunnysingh123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Your life does not get better by chance. It gets better by a change",
    portfolio: "http://goyette.info/",
    celeb: true,
  },
  {
    _id: uuid(),
    firstName: "Abhilash",
    lastName: "Gupta",
    username: "abhilashGupta",
    password: "abhilashGupta123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Creating my own sunshine",
    portfolio: "http://metz.com/ut-et-officia-hic-a.html",
    celeb: false,
  },

  {
    _id: uuid(),
    firstName: "Sameer",
    lastName: "Khan",
    username: "sameerKhan",
    password: "sameerKhan123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "I practice what I post",
    portfolio: "http://www.tromp.biz/ipsa-ducimus-fuga-modi-incidunt-mollitia",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "Biswa",
    lastName: "Shah",
    username: "biswaShah",
    password: "biswaShah123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "We have tomorrows for reason",
    portfolio:
      "http://www.schinner.com/similique-eligendi-voluptas-ducimus-dicta",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "Neel",
    lastName: "Suri",
    username: "neelSuri",
    password: "neelSuri123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Captivated from life, showing it here",
    portfolio:
      "https://greenfelder.com/autem-maxime-reiciendis-ducimus-totam-facere-sint.html",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "Aarya",
    lastName: "Choudhary",
    username: "aaryaChoudhary",
    password: "aaryaChoudhary123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "In a world of worriers, be a warrior",
    portfolio: "http://www.sawayn.com/",
    celeb: true,
  },
  {
    _id: uuid(),
    firstName: "Nisha",
    lastName: "Patel",
    username: "nishaPatel",
    password: "nishaPatel123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Simplicity is the key to happiness",
    portfolio: "http://www.monahan.com/",
    celeb: false,
  },
  {
    _id: uuid(),
    firstName: "cosmos",
    lastName: "nova",
    username: "cosmos09",
    password: "cosmos09123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    avatar: "https://semantic-ui.com/images/avatar2/large/matthew.png",
    bio: "Creating a life, I love",
    portfolio: "http://keeling.org/cum-consectetur-dolore-possimus-aut",
    celeb: false,
  },
];
